apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: acdv41flb-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/acdv41flb-java-springboot-gitops